export const events = {

    '2023': [
      {
        id: '1y2023',
        title: "",
        image: "img/2023_Events/img1.jpg",
        link: "#",
      },
      {
        id: '2y2023',
        title: "",
        image: "img/2023_Events/img2.jpg",
        link: "#",
      },
      {
        id: '3y2023',
        title: "",
        image: "img/2023_Events/img4.jpg",
        link: "#",
      },
      {
        id: '4y2023',
        title: "",
        image: "img/2023_Events/img5.jpg",
        link: "#",
      },
      {
        id: '5y2023',
        title: "",
        image: "img/2023_Events/img5.jpg",
        link: "#",
      },
      {
        id: '6y2023',
        title: "",
        image: "img/2023_Events/img6.jpg",
        link: "#",
      },
      {
        id: '7y2023',
        title: "",
        image: "img/2023_Events/img7.jpg",
        link: "#",
      },
      {
        id: '8y2023',
        title: "",
        image: "img/2023_Events/img8.jpg",
        link: "#",
      },
      {
        id: '9y2023',
        title: "",
        image: "img/2023_Events/img9.jpg",
        link: "#",
      },
      {
        id: '10y2023',
        title: "",
        image: "img/2023_Events/img10.jpg",
        link: "#",
      },
      {
        id: '11y2023',
        title: "",
        image: "img/2023_Events/img11.jpg",
        link: "#",
      },
      {
        id: '12y2023',
        title: "",
        image: "img/2023_Events/img12.jpg",
        link: "#",
      },
      {
        id: '13y2023',
        title: "",
        image: "img/2023_Events/img13.jpg",
        link: "#",
      },
      {
        id: '14y2023',
        title: "",
        image: "img/2023_Events/img14.jpg",
        link: "#",
      },
      {
        id: '15y2023',
        title: "",
        image: "img/2023_Events/img15.jpg",
        link: "#",
      },
      {
        id: '16y2023',
        title: "",
        image: "img/2023_Events/img16.jpg",
        link: "#",
      },
      {
        id: '17y2023',
        title: "",
        image: "img/2023_Events/img17.jpg",
        link: "#",
      },
      {
        id: '18y2023',
        title: "",
        image: "img/2023_Events/img18.jpg",
        link: "#",
      },
      {
        id: '19y2023',
        title: "",
        image: "img/2023_Events/img19.jpg",
        link: "#",
      },
      {
        id: '20y2023',
        title: "",
        image: "img/2023_Events/img20.jpg",
        link: "#",
      },
      {
        id: '21y2023',
        title: "",
        image: "img/2023_Events/img21.jpg",
        link: "#",
      },
      {
        id: '22y2023',
        title: "",
        image: "img/2023_Events/img22.jpg",
        link: "#",
      },
    ],


    2024: [
      {
        id: '1y2023',
        title: "",
        image: "img/2024_Events/img1.jpg",
        link: "#",
      },
      {
        id: '2y2023',
        title: "",
        image: "img/2024_Events/img2.jpg",
        link: "#",
      },
      {
        id: '3y2023',
        title: "",
        image: "img/2024_Events/img4.jpg",
        link: "#",
      },
      {
        id: '4y2023',
        title: "",
        image: "img/2024_Events/img5.jpg",
        link: "#",
      },
      {
        id: '5y2023',
        title: "",
        image: "img/2024_Events/img5.jpg",
        link: "#",
      },
      {
        id: '6y2023',
        title: "",
        image: "img/2024_Events/img6.jpg",
        link: "#",
      },
      {
        id: '7y2023',
        title: "",
        image: "img/2024_Events/img7.jpg",
        link: "#",
      },
      {
        id: '8y2023',
        title: "",
        image: "img/2024_Events/img8.jpg",
        link: "#",
      },
      {
        id: '9y2023',
        title: "",
        image: "img/2024_Events/img9.jpg",
        link: "#",
      },
      {
        id: '10y2023',
        title: "",
        image: "img/2024_Events/img10.jpg",
        link: "#",
      },
      {
        id: '11y2023',
        title: "",
        image: "img/2024_Events/img11.jpg",
        link: "#",
      },
      {
        id: '12y2023',
        title: "",
        image: "img/2024_Events/img12.jpg",
        link: "#",
      },
      {
        id: '13y2023',
        title: "",
        image: "img/2024_Events/img13.jpg",
        link: "#",
      },
      {
        id: '14y2023',
        title: "",
        image: "img/2024_Events/img14.jpg",
        link: "#",
      },
      {
        id: '15y2023',
        title: "",
        image: "img/2024_Events/img15.jpg",
        link: "#",
      },
      {
        id: '16y2023',
        title: "",
        image: "img/2024_Events/img16.jpg",
        link: "#",
      },
      {
        id: '17y2023',
        title: "",
        image: "img/2024_Events/img17.jpg",
        link: "#",
      },
      {
        id: '18y2023',
        title: "",
        image: "img/2024_Events/img18.jpg",
        link: "#",
      },
      {
        id: '19y2023',
        title: "",
        image: "img/2024_Events/img19.jpg",
        link: "#",
      },
      {
        id: '20y2023',
        title: "",
        image: "img/2024_Events/img20.jpg",
        link: "#",
      },
      {
        id: '21y2023',
        title: "",
        image: "img/2024_Events/img21.jpg",
        link: "#",
      },
      {
        id: '22y2023',
        title: "",
        image: "img/2024_Events/img22.jpg",
        link: "#",
      },
      {
        id: '23y2023',
        title: "",
        image: "img/2024_Events/img23.jpg",
        link: "#",
      },
    ],

    2025: [
      {
        id: 1,
        title: "",
        image: "img/2023_Events/img4.jpg",
        link: "#",
      },
      {
        id: 2,
        title: "",
        image: "img/2023_Events/img5.jpg",
        link: "#",
      },
      {
        id: 3,
        title: "",
        image: "img/2023_Events/img6.jpg",
        link: "#",
      },
    ],
};
