export const events = {

    '2023': [
      {
        id: '1y2023',
        title: "",
        image: "img/2023_Events/img1.jpg",
        link: "#",
      },
      {
        id: '2y2023',
        title: "",
        image: "img/2023_Events/img2.jpg",
        link: "#",
      },
      {
        id: '3y2023',
        title: "",
        image: "img/2023_Events/img4.jpg",
        link: "#",
      },
      {
        id: '4y2023',
        title: "",
        image: "img/2023_Events/img5.jpg",
        link: "#",
      },
      {
        id: '5y2023',
        title: "",
        image: "img/2023_Events/img5.jpg",
        link: "#",
      },
      {
        id: '6y2023',
        title: "",
        image: "img/2023_Events/img6.jpg",
        link: "#",
      },
      {
        id: '7y2023',
        title: "",
        image: "img/2023_Events/img7.jpg",
        link: "#",
      },
      {
        id: '8y2023',
        title: "",
        image: "img/2023_Events/img8.jpg",
        link: "#",
      },
      {
        id: '9y2023',
        title: "",
        image: "img/2023_Events/img9.jpg",
        link: "#",
      },
      {
        id: '10y2023',
        title: "",
        image: "img/2023_Events/img10.jpg",
        link: "#",
      },
      {
        id: '11y2023',
        title: "",
        image: "img/2023_Events/img11.jpg",
        link: "#",
      },
      {
        id: '12y2023',
        title: "",
        image: "img/2023_Events/img12.jpg",
        link: "#",
      },
      {
        id: '13y2023',
        title: "",
        image: "img/2023_Events/img13.jpg",
        link: "#",
      },
      {
        id: '14y2023',
        title: "",
        image: "img/2023_Events/img14.jpg",
        link: "#",
      },
      {
        id: '15y2023',
        title: "",
        image: "img/2023_Events/img15.jpg",
        link: "#",
      },
      {
        id: '16y2023',
        title: "",
        image: "img/2023_Events/img16.jpg",
        link: "#",
      },
      {
        id: '17y2023',
        title: "",
        image: "img/2023_Events/img17.jpg",
        link: "#",
      },
      {
        id: '18y2023',
        title: "",
        image: "img/2023_Events/img18.jpg",
        link: "#",
      },
      {
        id: '19y2023',
        title: "",
        image: "img/2023_Events/img19.jpg",
        link: "#",
      },
      {
        id: '20y2023',
        title: "",
        image: "img/2023_Events/img20.jpg",
        link: "#",
      },
      {
        id: '21y2023',
        title: "",
        image: "img/2023_Events/img21.jpg",
        link: "#",
      },
      {
        id: '22y2023',
        title: "",
        image: "img/2023_Events/img22.jpg",
        link: "#",
      },
    ],


    2024: [
      {
        id: '1y2023',
        title: "",
        image: "img/2024_Events/img1.jpg",
        link: "#",
      },
      {
        id: '2y2023',
        title: "",
        image: "img/2024_Events/img2.jpg",
        link: "#",
      },
      {
        id: '3y2023',
        title: "",
        image: "img/2024_Events/img4.jpg",
        link: "#",
      },
      {
        id: '4y2023',
        title: "",
        image: "img/2024_Events/img5.jpg",
        link: "#",
      },
      {
        id: '5y2023',
        title: "",
        image: "img/2024_Events/img5.jpg",
        link: "#",
      },
      {
        id: '6y2023',
        title: "",
        image: "img/2024_Events/img6.jpg",
        link: "#",
      },
      {
        id: '7y2023',
        title: "",
        image: "img/2024_Events/img7.jpg",
        link: "#",
      },
      {
        id: '8y2023',
        title: "",
        image: "img/2024_Events/img8.jpg",
        link: "#",
      },
      {
        id: '9y2023',
        title: "",
        image: "img/2024_Events/img9.jpg",
        link: "#",
      },
      {
        id: '10y2023',
        title: "",
        image: "img/2024_Events/img10.jpg",
        link: "#",
      },
      {
        id: '11y2023',
        title: "",
        image: "img/2024_Events/img11.jpg",
        link: "#",
      },
      {
        id: '12y2023',
        title: "",
        image: "img/2024_Events/img12.jpg",
        link: "#",
      },
      {
        id: '13y2023',
        title: "",
        image: "img/2024_Events/img13.jpg",
        link: "#",
      },
      {
        id: '14y2023',
        title: "",
        image: "img/2024_Events/img14.jpg",
        link: "#",
      },
      {
        id: '15y2023',
        title: "",
        image: "img/2024_Events/img15.jpg",
        link: "#",
      },
      {
        id: '16y2023',
        title: "",
        image: "img/2024_Events/img16.jpg",
        link: "#",
      },
      {
        id: '17y2023',
        title: "",
        image: "img/2024_Events/img17.jpg",
        link: "#",
      },
      {
        id: '18y2023',
        title: "",
        image: "img/2024_Events/img18.jpg",
        link: "#",
      },
      {
        id: '19y2023',
        title: "",
        image: "img/2024_Events/img19.jpg",
        link: "#",
      },
      {
        id: '20y2023',
        title: "",
        image: "img/2024_Events/img20.jpg",
        link: "#",
      },
      {
        id: '21y2023',
        title: "",
        image: "img/2024_Events/img21.jpg",
        link: "#",
      },
      {
        id: '22y2023',
        title: "",
        image: "img/2024_Events/img22.jpg",
        link: "#",
      },
      {
        id: '23y2023',
        title: "",
        image: "img/2024_Events/img23.jpg",
        link: "#",
      },
    ],

    2025: [
      {
        id: 1,
        title: "",
        image: "img/2025_Events/img1.jpg",
        link: "#",
      },
      {
        id: 2,
        title: "",
        image: "img/2025_Events/img2.jpg",
        link: "#",
      },
      {
        id: 3,
        title: "",
        image: "img/2025_Events/img3.jpg",
        link: "#",
      },
      {
        id: 4,
        title: "",
        image: "img/2025_Events/img4.jpg",
        link: "#",
      },
      {
        id: 5,
        title: "",
        image: "img/2025_Events/img5.jpg",
        link: "#",
      },
      {
        id: 6,
        title: "",
        image: "img/2025_Events/img6.jpg",
        link: "#",
      },
      {
        id: 7,
        title: "",
        image: "img/2025_Events/img7.jpg",
        link: "#",
      },
      {
        id: 8,
        title: "",
        image: "img/2025_Events/img8.jpg",
        link: "#",
      },
      {
        id: 9,
        title: "",
        image: "img/2025_Events/img9.jpg",
        link: "#",
      },
      {
        id: 10,
        title: "",
        image: "img/2025_Events/img10.jpg",
        link: "#",
      },
      {
        id: 11,
        title: "",
        image: "img/2025_Events/img11.jpg",
        link: "#",
      },
      {
        id: 12,
        title: "",
        image: "img/2025_Events/img12.jpg",
        link: "#",
      },
      {
        id: 13,
        title: "",
        image: "img/2025_Events/img13.jpg",
        link: "#",
      },
      {
        id: 14,
        title: "",
        image: "img/2025_Events/img14.jpg",
        link: "#",
      },
      {
        id: 15,
        title: "",
        image: "img/2025_Events/img15.jpg",
        link: "#",
      },
      {
        id: 16,
        title: "",
        image: "img/2025_Events/img16.jpg",
        link: "#",
      },
      {
        id: 17,
        title: "",
        image: "img/2025_Events/img17.jpg",
        link: "#",
      },
      {
        id: 18,
        title: "",
        image: "img/2025_Events/img18.jpg",
        link: "#",
      },
      {
        id: 19,
        title: "",
        image: "img/2025_Events/img19.jpg",
        link: "#",
      },
      {
        id: 20,
        title: "",
        image: "img/2025_Events/img20.jpg",
        link: "#",
      },
      {
        id: 21,
        title: "",
        image: "img/2025_Events/img21.jpg",
        link: "#",
      },
      {
        id: 22,
        title: "",
        image: "img/2025_Events/img22.jpg",
        link: "#",
      },
      {
        id: 23,
        title: "",
        image: "img/2025_Events/img23.jpg",
        link: "#",
      },
      {
        id: 24,
        title: "",
        image: "img/2025_Events/img24.jpg",
        link: "#",
      },
      {
        id: 25,
        title: "",
        image: "img/2025_Events/img25.jpg",
        link: "#",
      },
      {
        id: 26,
        title: "",
        image: "img/2025_Events/img26.jpg",
        link: "#",
      },
      {
        id: 27,
        title: "",
        image: "img/2025_Events/img27.jpg",
        link: "#",
      },
      {
        id: 28,
        title: "",
        image: "img/2025_Events/img28.jpg",
        link: "#",
      },
      {
        id: 29,
        title: "",
        image: "img/2025_Events/img29.jpg",
        link: "#",
      },
      {
        id: 30,
        title: "",
        image: "img/2025_Events/img30.jpg",
        link: "#",
      },
      {
        id: 31,
        title: "",
        image: "img/2025_Events/img31.jpg",
        link: "#",
      },
      {
        id: 32,
        title: "",
        image: "img/2025_Events/img32.jpg",
        link: "#",
      },
      {
        id: 33,
        title: "",
        image: "img/2025_Events/img33.jpg",
        link: "#",
      },
      {
        id: 34,
        title: "",
        image: "img/2025_Events/img34.jpg",
        link: "#",
      },
      {
        id: 35,
        title: "",
        image: "img/2025_Events/img35.jpg",
        link: "#",
      },
      {
        id: 36,
        title: "",
        image: "img/2025_Events/img36.jpg",
        link: "#",
      },
      {
        id: 37,
        title: "",
        image: "img/2025_Events/img37.jpg",
        link: "#",
      },
      {
        id: 38,
        title: "",
        image: "img/2025_Events/img38.jpg",
        link: "#",
      },
      {
        id: 39,
        title: "",
        image: "img/2025_Events/img39.jpg",
        link: "#",
      },
      {
        id: 40,
        title: "",
        image: "img/2025_Events/img40.jpg",
        link: "#",
      },
      {
        id: 41,
        title: "",
        image: "img/2025_Events/img41.jpg",
        link: "#",
      },
      {
        id: 42,
        title: "",
        image: "img/2025_Events/img42.jpg",
        link: "#",
      },
      {
        id: 43,
        title: "",
        image: "img/2025_Events/img43.jpg",
        link: "#",
      },
      {
        id: 44,
        title: "",
        image: "img/2025_Events/img44.jpg",
        link: "#",
      },
      {
        id: 45,
        title: "",
        image: "img/2025_Events/img45.jpg",
        link: "#",
      },
      {
        id: 46,
        title: "",
        image: "img/2025_Events/img46.jpg",
        link: "#",
      },
      {
        id: 47,
        title: "",
        image: "img/2025_Events/img47.jpg",
        link: "#",
      },
      {
        id: 48,
        title: "",
        image: "img/2025_Events/img48.jpg",
        link: "#",
      },
      {
        id: 49,
        title: "",
        image: "img/2025_Events/img49.jpg",
        link: "#",
      },
      {
        id: 50,
        title: "",
        image: "img/2025_Events/img50.jpg",
        link: "#",
      },
      {
        id: 51,
        title: "",
        image: "img/2025_Events/img51.jpg",
        link: "#",
      },
      {
        id: 52,
        title: "",
        image: "img/2025_Events/img52.jpg",
        link: "#",
      },
      {
        id: 53,
        title: "",
        image: "img/2025_Events/img53.jpg",
        link: "#",
      },
      {
        id: 54,
        title: "",
        image: "img/2025_Events/img54.jpg",
        link: "#",
      },
      {
        id: 55,
        title: "",
        image: "img/2025_Events/img55.jpg",
        link: "#",
      },
      {
        id: 56,
        title: "",
        image: "img/2025_Events/img56.jpg",
        link: "#",
      },
      {
        id: 57,
        title: "",
        image: "img/2025_Events/img57.jpg",
        link: "#",
      },
      {
        id: 58,
        title: "",
        image: "img/2025_Events/img58.jpg",
        link: "#",
      },
      {
        id: 59,
        title: "",
        image: "img/2025_Events/img59.jpg",
        link: "#",
      },
      {
        id: 60,
        title: "",
        image: "img/2025_Events/img60.jpg",
        link: "#",
      },
      {
        id: 61,
        title: "",
        image: "img/2025_Events/img61.jpg",
        link: "#",
      },
      {
        id: 62,
        title: "",
        image: "img/2025_Events/img62.jpg",
        link: "#",
      },
      {
        id: 63,
        title: "",
        image: "img/2025_Events/img63.jpg",
        link: "#",
      },
      {
        id: 64,
        title: "",
        image: "img/2025_Events/img64.jpg",
        link: "#",
      },
      {
        id:   65,
        title: "",
        image: "img/2025_Events/img65.jpg",
        link: "#",
      },
      {
        id: 66,
        title: "",
        image: "img/2025_Events/img66.jpg",
        link: "#",
      },
    ],
};
